# Generated by Django 2.2.4 on 2020-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STOCKES', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kosdaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('fluctuation', models.FloatField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
    ]
