# Generated by Django 2.2.4 on 2020-06-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STOCKES', '0002_kosdaq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kosdaq',
            name='price',
        ),
        migrations.RemoveField(
            model_name='kospi',
            name='price',
        ),
    ]
